v["Rout","2"]=v["unnamed_net5"];
v["Cout","1"]=v["unnamed_net5"];
v["Rout","1"]=v["GND"];
v["Cgd","2"]=v["GND"];
v["Q1","D"]=v["GND"];
v["Cgd","1"]=v["unnamed_net4"];
v["Cgs","1"]=v["unnamed_net4"];
v["Q1","G"]=v["unnamed_net4"];
v["Rop","2"]=v["unnamed_net4"];
v["Rop","1"]=v["unnamed_net3"];
v["U1","3"]=v["unnamed_net3"];
v["stim","1"]=v["unnamed_net2"];
v["out","1"]=v["unnamed_net2"];
v["Cout","2"]=v["unnamed_net2"];
v["Cgs","2"]=v["unnamed_net2"];
v["Q1","S"]=v["unnamed_net2"];
v["U1","2"]=v["unnamed_net2"];
v["in","1"]=v["unnamed_net1"];
v["U1","1"]=v["unnamed_net1"];
nodeEquations={
i["Rout","2"]+i["Cout","1"]==0,
i["Cgd","1"]+i["Cgs","1"]+i["Q1","G"]+i["Rop","2"]==0,
i["Rop","1"]+i["U1","3"]==0,
i["stim","1"]+i["out","1"]+i["Cout","2"]+i["Cgs","2"]+i["Q1","S"]+i["U1","2"]==0,
i["in","1"]+i["U1","1"]==0};
modelEquations={
voltage[value->in]["in"],
current[value->stim]["stim"],
testpoint[value->out]["out"],
resistor[value->rout]["Rout"],
capacitor[value->cout]["Cout"],
capacitor[value->cgd]["Cgd"],
capacitor[value->cgs]["Cgs"],
fet[value->gm]["Q1"],
resistor[value->rop]["Rop"],
opamp[bandwidth->bw]["U1"]};
variables={
v["unnamed_net5"],
v["unnamed_net4"],
v["unnamed_net3"],
v["unnamed_net2"],
v["unnamed_net1"],
i["Rout","2"],
i["Cout","1"],
i["Rout","1"],
i["Cgd","2"],
i["Q1","D"],
i["Cgd","1"],
i["Cgs","1"],
i["Q1","G"],
i["Rop","2"],
i["Rop","1"],
i["U1","3"],
i["stim","1"],
i["out","1"],
i["Cout","2"],
i["Cgs","2"],
i["Q1","S"],
i["U1","2"],
i["in","1"],
i["U1","1"]};
