all: preview.sty

preview.sty: preview.ins preview.dtx
	tex preview.ins

clean:
	rm -f preview.sty prauctex.cfg prauctex.def prcounters.def preview.drv prfootnotes.def prlyx.def prshowbox.def prshowlabels.def prtightpage.def prtracingall.def preview.log
